correction

diff --git a/add b/add
--- a/add
+++ b/add
@@ -16,23 +16,15 @@ git commit -m "$P"
 error=$(git commit -m "$P" 2>&1 >/dev/null)
 if [ $? -ne 0 ]; then
     echo -e "${red}Commit failed${reset_color}"
-    if echo "$error" | grep -q "
-*** Please tell me who you are.
-
-Run
-
-  git config --global user.email \"you@example.com\"
-  git config --global user.name \"Your Name\"
-
-to set your account's default identity.
-Omit --global to set the identity only in this repository.
-
-fatal: unable to auto-detect email address (got 'root@2151e432f63e.(none)')"; then
+    while
+	    echo "$error" | grep -q ")"
+    do
 	    git config --global user.email "h.nyahoja@alustudent.com"
 	    git config --global user.name "Humphrey Nyahoja"
-    else
-	    exit 1
-    fi
+    done
+    echo -e "${green} Email and name .....updated${reset_color}"
+    exit 1
+    
 
 else
 	git push
