ohiyogufyh

diff --git a/add b/add
--- a/add
+++ b/add
@@ -1,14 +1,40 @@
-#!/bin/zsh
-autoload -U colors && colors
+#!/bin/bash
+
+
+red='\033[31m'
+green='\033[0;32m'
+reset_color='\033[0m'
+
+
 git add .
 echo "Write the commit message: "
 read -r P
+
+
 git commit -m "$P"
 
+error=$(git commit -m "$P" 2>&1 >/dev/null)
 if [ $? -ne 0 ]; then
-    echo -e "${fg[red]}Commit failed${reset_color}"
-    exit 1
-else:
+    echo -e "${red}Commit failed${reset_color}"
+    if echo "$error" | grep -q "
+*** Please tell me who you are.
+
+Run
+
+  git config --global user.email \"you@example.com\"
+  git config --global user.name \"Your Name\"
+
+to set your account's default identity.
+Omit --global to set the identity only in this repository.
+
+fatal: unable to auto-detect email address (got 'root@2151e432f63e.(none)')"; then
+	    git config --global user.email "h.nyahoja@alustudent.com"
+	    git config --global user.name "Humphrey Nyahoja"
+    else
+	    exit 1
+    fi
+
+else
 	git push
-	echo -e "${fg[green]}Pushed to remote${reset_color}"
+	echo -e "${green}Pushed to remote${reset_color}"
 fi
